import { useState, useEffect, useRef, useCallback } from 'react';
import { useSearchParams } from 'react-router-dom';
import { useMutation } from '@tanstack/react-query';
import { saleService } from '../services/api/saleService';
import { inventoryService } from '../services/api/inventoryService';
import { purchaseOrderService } from '../services/api/purchaseOrderService';
import { toast } from 'react-hot-toast';
import {
  FileText,
  Download,
  Calendar,
  Filter,
  TrendingUp,
  Package,
  ShoppingCart,
  DollarSign,
  BarChart3,
  Loader2
} from 'lucide-react';

const SALES_PAGE_SIZE = 50;
const INVENTORY_PAGE_SIZE = 50;

const getCustomerName = (customer) => {
  if (!customer) return 'Cliente General';
  if (customer.type === 'natural') return `${customer.firstName || ''} ${customer.lastName || ''}`.trim() || 'Sin nombre';
  return customer.businessName || customer.tradeName || 'Sin nombre';
};

const getSaleTypeLabel = (type) => {
  if (type === 'mixed') return 'Mixta';
  if (type === 'credit') return 'Crédito';
  return 'Contado';
};

const ReportsPage = () => {
  const [searchParams] = useSearchParams();
  const autoGenerated = useRef(false);

  const paramType = searchParams.get('type');
  const paramStart = searchParams.get('start');
  const paramEnd = searchParams.get('end');

  const [reportType, setReportType] = useState(paramType || 'sales');
  const [dateRange, setDateRange] = useState({
    start_date: paramStart || new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString().split('T')[0],
    end_date: paramEnd || new Date().toISOString().split('T')[0]
  });

  // Sales state (independent of mutation)
  const [salesRows, setSalesRows] = useState([]);
  const [salesPage, setSalesPage] = useState(1);
  const [hasMoreSales, setHasMoreSales] = useState(false);
  const [loadingMoreSales, setLoadingMoreSales] = useState(false);
  const [salesStats, setSalesStats] = useState(null);
  const [salesLoading, setSalesLoading] = useState(false);
  const [exportingCSV, setExportingCSV] = useState(false);
  const salesAdjustedRange = useRef(null);

  // Inventory state (independent of mutation, like sales)
  const [inventoryRows, setInventoryRows] = useState([]);
  const [inventoryPage, setInventoryPage] = useState(1);
  const [hasMoreInventory, setHasMoreInventory] = useState(false);
  const [loadingMoreInventory, setLoadingMoreInventory] = useState(false);
  const [inventoryStats, setInventoryStats] = useState(null);
  const [inventoryLoading, setInventoryLoading] = useState(false);

  const reportTypes = [
    { value: 'sales', label: 'Reporte de Ventas', icon: DollarSign },
    { value: 'inventory', label: 'Inventario Valorizado', icon: Package },
    { value: 'purchases', label: 'Reporte de Compras', icon: ShoppingCart },
    { value: 'top_products', label: 'Productos Más Vendidos', icon: TrendingUp },
    { value: 'product_sales', label: 'Ventas por Producto', icon: BarChart3 },
    { value: 'low_stock', label: 'Productos con Bajo Stock', icon: Package }
  ];

  const getAdjustedRange = (range) => ({
    start_date: range.start_date + 'T00:00:00',
    end_date: range.end_date + 'T23:59:59'
  });

  const SALES_STATUS_FILTER = 'completed,pending';

  const generateSalesReport = useCallback(async (range) => {
    const adjusted = { ...getAdjustedRange(range), status: SALES_STATUS_FILTER };
    salesAdjustedRange.current = adjusted;
    setSalesStats(null);
    setSalesRows([]);
    setSalesLoading(true);
    try {
      const [statsRes, salesRes] = await Promise.all([
        saleService.getSalesStats({ ...adjusted, summary_only: 'true' }),
        saleService.getSales({ ...adjusted, page: 1, limit: SALES_PAGE_SIZE })
      ]);
      const total = statsRes.stats?.totalSales || 0;
      const cop = statsRes.stats?.totalRevenueCOP || 0;
      setSalesStats({
        total_sales: total,
        total_amount_cop: cop,
        average_ticket_cop: total > 0 ? cop / total : 0,
      });
      const rows = salesRes.sales || [];
      const pagination = salesRes.pagination || {};
      setSalesRows(rows);
      setSalesPage(1);
      setHasMoreSales(pagination.page < pagination.totalPages);
    } catch (e) {
      console.error('Error generating sales report:', e);
      toast.error('Error al generar el reporte de ventas');
    } finally {
      setSalesLoading(false);
    }
  }, []);

  const processInventoryItem = (item) => {
    const qty = parseFloat(item.quantity) || 0;
    const cost = parseFloat(item.product?.cost) || 0;
    const value = qty * cost;
    return { ...item, quantity: qty, value };
  };

  const generateInventoryReport = useCallback(async () => {
    setInventoryStats(null);
    setInventoryRows([]);
    setInventoryLoading(true);
    try {
      const res = await inventoryService.getAll({ page: 1, limit: INVENTORY_PAGE_SIZE });
      const items = (res.data || []).map(processInventoryItem);
      const pagination = res.pagination || {};
      setInventoryRows(items);
      setInventoryPage(1);
      setHasMoreInventory(pagination.page < pagination.totalPages);
      setInventoryStats({
        total_items: pagination.total || items.length,
        total_value: null,
        total_quantity: null
      });
    } catch (e) {
      console.error('Error generating inventory report:', e);
      toast.error('Error al generar el reporte de inventario');
    } finally {
      setInventoryLoading(false);
    }
  }, []);

  const loadMoreInventory = useCallback(async () => {
    if (loadingMoreInventory || !hasMoreInventory) return;
    try {
      setLoadingMoreInventory(true);
      const nextPage = inventoryPage + 1;
      const res = await inventoryService.getAll({ page: nextPage, limit: INVENTORY_PAGE_SIZE });
      const items = (res.data || []).map(processInventoryItem);
      const pagination = res.pagination || {};
      setInventoryRows(prev => [...prev, ...items]);
      setInventoryPage(nextPage);
      setHasMoreInventory(pagination.page < pagination.totalPages);
    } catch (e) {
      console.error('Error loading more inventory:', e);
    } finally {
      setLoadingMoreInventory(false);
    }
  }, [loadingMoreInventory, hasMoreInventory, inventoryPage]);

  const generateReportMutation = useMutation({
    mutationFn: async ({ type, dateRange: range }) => {
      switch (type) {
        case 'purchases': {
          const purchaseOrders = await purchaseOrderService.getAll({
            start_date: range.start_date + 'T00:00:00',
            end_date: range.end_date + 'T23:59:59',
            limit: 1000
          });
          const poList = purchaseOrders.data || purchaseOrders.purchaseOrders || [];
          const totalAmount = poList.reduce((sum, po) => sum + parseFloat(po.total || 0), 0);
          return {
            stats: {
              total_orders: poList.length,
              total_amount: totalAmount,
              average_order: poList.length > 0 ? totalAmount / poList.length : 0
            },
            data: poList
          };
        }
        case 'top_products': {
          const statsData = await saleService.getSalesStats({
            start_date: range.start_date + 'T00:00:00',
            end_date: range.end_date + 'T23:59:59',
            top_limit: 50
          });
          const topProducts = (statsData.stats?.topProducts || []).map(tp => ({
            product: tp.product,
            total_quantity: parseFloat(tp.dataValues?.total_quantity || tp.total_quantity || 0),
            total_amount: parseFloat(tp.dataValues?.total_amount || tp.total_amount || 0)
          }));
          return {
            stats: {
              total_products: topProducts.length,
              total_revenue: topProducts.reduce((sum, p) => sum + p.total_amount, 0),
              total_units_sold: topProducts.reduce((sum, p) => sum + p.total_quantity, 0)
            },
            data: topProducts
          };
        }
        case 'product_sales': {
          const productSalesData = await saleService.getProductSales({
            start_date: range.start_date + 'T00:00:00',
            end_date: range.end_date + 'T23:59:59',
          });
          const items = (productSalesData.data || []).map(item => ({
            product: item.product,
            total_quantity: parseFloat(item.dataValues?.total_quantity || item.total_quantity || 0),
            num_sales: parseInt(item.dataValues?.num_sales || item.num_sales || 0),
            total_usd: parseFloat(item.dataValues?.total_usd || item.total_usd || 0),
            total_cop: Math.round(parseFloat(item.dataValues?.total_cop || item.total_cop || 0)),
          }));
          return {
            stats: {
              total_products: items.length,
              total_units: items.reduce((sum, p) => sum + p.total_quantity, 0),
              total_usd: items.reduce((sum, p) => sum + p.total_usd, 0),
              total_cop: items.reduce((sum, p) => sum + p.total_cop, 0),
            },
            data: items
          };
        }
        case 'low_stock': {
          const lowStockData = await inventoryService.getLowStock({ limit: 1000 });
          const items = lowStockData.data || lowStockData.inventory || [];
          return {
            stats: { critical_items: items.length },
            data: items
          };
        }
        default:
          return { stats: null, data: [] };
      }
    },
    onError: (error) => {
      toast.error('Error al generar el reporte');
      console.error('Error generating report:', error);
    }
  });

  const loadMoreSales = useCallback(async () => {
    if (loadingMoreSales || !hasMoreSales || !salesAdjustedRange.current) return;
    try {
      setLoadingMoreSales(true);
      const nextPage = salesPage + 1;
      const res = await saleService.getSales({ ...salesAdjustedRange.current, page: nextPage, limit: SALES_PAGE_SIZE });
      const rows = res.sales || [];
      const pagination = res.pagination || {};
      setSalesRows(prev => [...prev, ...rows]);
      setSalesPage(nextPage);
      setHasMoreSales(pagination.page < pagination.totalPages);
    } catch (e) {
      console.error('Error loading more sales:', e);
    } finally {
      setLoadingMoreSales(false);
    }
  }, [loadingMoreSales, hasMoreSales, salesPage]);

  // Auto-generate report when URL has params
  useEffect(() => {
    if (paramType && !autoGenerated.current) {
      autoGenerated.current = true;
      if (reportType === 'sales') {
        generateSalesReport(dateRange);
      } else if (reportType === 'inventory') {
        generateInventoryReport();
      } else {
        generateReportMutation.mutate({ type: reportType, dateRange });
      }
    }
  }, []);

  const reportResult = generateReportMutation.data;
  const stats = reportType === 'sales' ? salesStats : reportType === 'inventory' ? inventoryStats : (reportResult?.stats ?? null);
  const reportData = reportType === 'sales' ? salesRows : reportType === 'inventory' ? inventoryRows : (reportResult?.data ?? null);
  const loading = reportType === 'sales' ? salesLoading : reportType === 'inventory' ? inventoryLoading : generateReportMutation.isPending;

  const fetchAllSalesForExport = async () => {
    if (!salesAdjustedRange.current) return [];
    const allSales = [];
    let page = 1;
    let hasMore = true;
    while (hasMore) {
      const res = await saleService.getSales({ ...salesAdjustedRange.current, page, limit: 200 });
      const rows = res.sales || [];
      allSales.push(...rows);
      const pagination = res.pagination || {};
      hasMore = pagination.page < pagination.totalPages;
      page++;
    }
    return allSales;
  };

  const fetchAllInventoryForExport = async () => {
    const allItems = [];
    let page = 1;
    let hasMore = true;
    while (hasMore) {
      const res = await inventoryService.getAll({ page, limit: 200 });
      const items = (res.data || []).map(processInventoryItem);
      allItems.push(...items);
      const pagination = res.pagination || {};
      hasMore = pagination.page < pagination.totalPages;
      page++;
    }
    return allItems;
  };

  const buildInventoryCSV = (items) => {
    let csv = 'SKU,Producto,Almacén,Cant. Total,Existencia (Paquetes),Existencia (Unidades),Uds/Paquete,Costo Unitario,Valor Total\n';
    items.forEach(item => {
      const presentations = item.product?.presentations || [];
      const defaultPresentation = presentations.find(p => p.is_default) || presentations[0];
      const unitsPerPackage = defaultPresentation?.units_per_package || 1;
      const totalUnits = item.quantity || 0;
      const stockPackages = Math.floor(totalUnits / unitsPerPackage);
      const stockRemainingUnits = totalUnits % unitsPerPackage;
      csv += `"${item.product?.sku || ''}","${item.product?.name || ''}","${item.warehouse?.name || ''}",${totalUnits},${stockPackages},${stockRemainingUnits},${unitsPerPackage},${item.product?.cost || 0},${item.value || 0}\n`;
    });
    return csv;
  };

  const buildSalesCSV = (sales) => {
    let csv = 'Número,Fecha,Cliente,Tipo,Estado,Total COP\n';
    sales.forEach(sale => {
      const rate = parseFloat(sale.exchange_rate) || 1;
      const totalCOP = Math.round((parseFloat(sale.total) || 0) * rate);
      csv += `"${sale.sale_number}","${new Date(sale.sale_date).toLocaleDateString()}","${getCustomerName(sale.customer)}","${getSaleTypeLabel(sale.sale_type)}","${sale.status}",${totalCOP}\n`;
    });
    return csv;
  };

  const downloadCSV = (csvContent, filename) => {
    const blob = new Blob(['\uFEFF' + csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = filename;
    link.click();
  };

  const exportToCSV = async () => {
    if (!reportData || reportData.length === 0) {
      toast.error('No hay datos para exportar');
      return;
    }

    let csvContent = '';
    let filename = '';

    switch (reportType) {
      case 'sales': {
        setExportingCSV(true);
        try {
          const allSales = await fetchAllSalesForExport();
          csvContent = buildSalesCSV(allSales);
          filename = `reporte_ventas_${dateRange.start_date}_${dateRange.end_date}.csv`;
          toast.success(`${allSales.length} ventas exportadas`);
        } catch (e) {
          console.error('Error exporting sales CSV:', e);
          toast.error('Error al exportar ventas');
          return;
        } finally {
          setExportingCSV(false);
        }
        break;
      }
      case 'inventory': {
        setExportingCSV(true);
        try {
          const allInventory = await fetchAllInventoryForExport();
          csvContent = buildInventoryCSV(allInventory);
          filename = `inventario_valorizado_${new Date().toISOString().split('T')[0]}.csv`;
          toast.success(`${allInventory.length} items exportados`);
        } catch (e) {
          console.error('Error exporting inventory CSV:', e);
          toast.error('Error al exportar inventario');
          return;
        } finally {
          setExportingCSV(false);
        }
        break;
      }
      case 'purchases':
        csvContent = generatePurchasesCSV();
        filename = `reporte_compras_${dateRange.start_date}_${dateRange.end_date}.csv`;
        break;
      case 'top_products':
        csvContent = generateTopProductsCSV();
        filename = `productos_mas_vendidos_${dateRange.start_date}_${dateRange.end_date}.csv`;
        break;
      case 'product_sales':
        csvContent = generateProductSalesCSV();
        filename = `ventas_por_producto_${dateRange.start_date}_${dateRange.end_date}.csv`;
        break;
      case 'low_stock':
        csvContent = generateLowStockCSV();
        filename = `productos_bajo_stock_${new Date().toISOString().split('T')[0]}.csv`;
        break;
      default:
        return;
    }

    downloadCSV(csvContent, filename);
  };

  const generatePurchasesCSV = () => {
    let csv = 'Número,Fecha,Proveedor,Estado,Moneda,Total\n';
    reportData.forEach(po => {
      csv += `"${po.order_number}","${new Date(po.order_date).toLocaleDateString()}","${po.supplier?.name || ''}","${po.status}","${po.currency}",${po.total}\n`;
    });
    return csv;
  };

  const generateTopProductsCSV = () => {
    let csv = 'SKU,Producto,Cantidad Vendida,Monto Total\n';
    reportData.forEach(item => {
      csv += `"${item.product?.sku || ''}","${item.product?.name || ''}",${item.total_quantity},${item.total_amount}\n`;
    });
    return csv;
  };

  const generateProductSalesCSV = () => {
    let csv = 'SKU,Producto,Cant. Vendida,# Ventas,Total USD,Total COP\n';
    reportData.forEach(item => {
      csv += `"${item.product?.sku || ''}","${item.product?.name || ''}",${item.total_quantity},${item.num_sales},${parseFloat(item.total_usd || 0).toFixed(2)},${Math.round(item.total_cop || 0)}\n`;
    });
    return csv;
  };

  const generateLowStockCSV = () => {
    let csv = 'SKU,Producto,Almacén,Cant. Total,Existencia (Paquetes),Existencia (Unidades),Uds/Paquete,Stock Mínimo,Estado\n';
    reportData.forEach(item => {
      const presentations = item.product?.presentations || [];
      const defaultPresentation = presentations.find(p => p.is_default) || presentations[0];
      const unitsPerPackage = defaultPresentation?.units_per_package || 1;
      const totalUnits = item.quantity || 0;
      const stockPackages = Math.floor(totalUnits / unitsPerPackage);
      const stockRemainingUnits = totalUnits % unitsPerPackage;
      csv += `"${item.product?.sku || ''}","${item.product?.name || ''}","${item.warehouse?.name || ''}",${totalUnits},${stockPackages},${stockRemainingUnits},${unitsPerPackage},${item.product?.minimum_stock || 0},"Crítico"\n`;
    });
    return csv;
  };

  const renderStatsCards = () => {
    if (!stats) return null;
    switch (reportType) {
      case 'sales':
        return (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
            <div className="bg-white rounded-lg shadow p-4">
              <div className="text-sm text-gray-600">Total Ventas</div>
              <div className="text-2xl font-bold text-gray-900">{stats.total_sales}</div>
            </div>
            <div className="bg-white rounded-lg shadow p-4">
              <div className="text-sm text-gray-600">Monto Total</div>
              <div className="text-2xl font-bold text-gray-900">COP {Math.round(stats.total_amount_cop || 0).toLocaleString('de-DE')}</div>
            </div>
            <div className="bg-white rounded-lg shadow p-4">
              <div className="text-sm text-gray-600">Ticket Promedio</div>
              <div className="text-2xl font-bold text-gray-900">COP {Math.round(stats.average_ticket_cop || 0).toLocaleString('de-DE')}</div>
            </div>
          </div>
        );
      case 'inventory':
        return (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
            <div className="bg-white rounded-lg shadow p-4">
              <div className="text-sm text-gray-600">Total Items</div>
              <div className="text-2xl font-bold text-gray-900">{stats.total_items}</div>
            </div>
          </div>
        );
      case 'purchases':
        return (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
            <div className="bg-white rounded-lg shadow p-4">
              <div className="text-sm text-gray-600">Total Órdenes</div>
              <div className="text-2xl font-bold text-gray-900">{stats.total_orders}</div>
            </div>
            <div className="bg-white rounded-lg shadow p-4">
              <div className="text-sm text-gray-600">Monto Total</div>
              <div className="text-2xl font-bold text-gray-900">$ {parseFloat(stats.total_amount || 0).toFixed(2)}</div>
            </div>
            <div className="bg-white rounded-lg shadow p-4">
              <div className="text-sm text-gray-600">Promedio por Orden</div>
              <div className="text-2xl font-bold text-gray-900">$ {parseFloat(stats.average_order || 0).toFixed(2)}</div>
            </div>
          </div>
        );
      case 'top_products':
        return (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
            <div className="bg-white rounded-lg shadow p-4">
              <div className="text-sm text-gray-600">Total Productos</div>
              <div className="text-2xl font-bold text-gray-900">{stats.total_products}</div>
            </div>
            <div className="bg-white rounded-lg shadow p-4">
              <div className="text-sm text-gray-600">Unidades Vendidas</div>
              <div className="text-2xl font-bold text-gray-900">{stats.total_units_sold}</div>
            </div>
            <div className="bg-white rounded-lg shadow p-4">
              <div className="text-sm text-gray-600">Ingresos Totales</div>
              <div className="text-2xl font-bold text-gray-900">$ {parseFloat(stats.total_revenue || 0).toFixed(2)}</div>
            </div>
          </div>
        );
      case 'product_sales':
        return (
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
            <div className="bg-white rounded-lg shadow p-4">
              <div className="text-sm text-gray-600">Total Productos</div>
              <div className="text-2xl font-bold text-gray-900">{stats.total_products}</div>
            </div>
            <div className="bg-white rounded-lg shadow p-4">
              <div className="text-sm text-gray-600">Total Unidades</div>
              <div className="text-2xl font-bold text-gray-900">{stats.total_units}</div>
            </div>
            <div className="bg-white rounded-lg shadow p-4">
              <div className="text-sm text-gray-600">Total USD</div>
              <div className="text-2xl font-bold text-gray-900">$ {parseFloat(stats.total_usd || 0).toFixed(2)}</div>
            </div>
            <div className="bg-white rounded-lg shadow p-4">
              <div className="text-sm text-gray-600">Total COP</div>
              <div className="text-2xl font-bold text-gray-900">COP {Math.round(stats.total_cop || 0).toLocaleString('de-DE')}</div>
            </div>
          </div>
        );
      case 'low_stock':
        return (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
            <div className="bg-white rounded-lg shadow p-4">
              <div className="text-sm text-gray-600">Items Críticos</div>
              <div className="text-2xl font-bold text-red-600">{stats.critical_items}</div>
            </div>
          </div>
        );
      default:
        return null;
    }
  };

  // Infinite scroll via IntersectionObserver
  const sentinelRef = useRef(null);
  useEffect(() => {
    if (reportType !== 'sales' || !hasMoreSales) return;
    const el = sentinelRef.current;
    if (!el) return;
    const observer = new IntersectionObserver(
      ([entry]) => { if (entry.isIntersecting) loadMoreSales(); },
      { rootMargin: '200px' }
    );
    observer.observe(el);
    return () => observer.disconnect();
  }, [reportType, hasMoreSales, loadMoreSales]);

  const inventorySentinelRef = useRef(null);
  useEffect(() => {
    if (reportType !== 'inventory' || !hasMoreInventory) return;
    const el = inventorySentinelRef.current;
    if (!el) return;
    const observer = new IntersectionObserver(
      ([entry]) => { if (entry.isIntersecting) loadMoreInventory(); },
      { rootMargin: '200px' }
    );
    observer.observe(el);
    return () => observer.disconnect();
  }, [reportType, hasMoreInventory, loadMoreInventory]);

  const renderReportTable = () => {
    if (!reportData || reportData.length === 0) {
      return (
        <div className="text-center py-12 text-gray-500">
          No hay datos para mostrar
        </div>
      );
    }

    switch (reportType) {
      case 'sales':
        return (
          <div>
            <table className="min-w-full divide-y divide-gray-200">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Número</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Fecha</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Cliente</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Tipo</th>
                  <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase">Total</th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {salesRows.map((sale, index) => (
                  <tr key={index}>
                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{sale.sale_number}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{new Date(sale.sale_date).toLocaleDateString()}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{getCustomerName(sale.customer)}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{getSaleTypeLabel(sale.sale_type)}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium text-gray-900">COP {Math.round((parseFloat(sale.total) || 0) * (parseFloat(sale.exchange_rate) || 1)).toLocaleString('de-DE')}</td>
                  </tr>
                ))}
              </tbody>
            </table>
            {loadingMoreSales && (
              <div className="flex items-center justify-center py-4">
                <Loader2 className="w-5 h-5 animate-spin text-gray-400" />
                <span className="ml-2 text-sm text-gray-500">Cargando más ventas...</span>
              </div>
            )}
            {!hasMoreSales && salesRows.length > 0 && (
              <div className="text-center py-3 text-xs text-gray-400">
                {salesRows.length} ventas cargadas
              </div>
            )}
            {hasMoreSales && <div ref={sentinelRef} className="h-1" />}
          </div>
        );
      case 'inventory':
        return (
          <div>
            <table className="min-w-full divide-y divide-gray-200">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">SKU</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Producto</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Almacén</th>
                  <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase">Cantidad</th>
                  <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase">Costo Unit.</th>
                  <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase">Valor Total</th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {inventoryRows.map((item, index) => (
                  <tr key={index}>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{item.product?.sku}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{item.product?.name}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{item.warehouse?.name}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-right text-sm text-gray-900">{item.quantity}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-right text-sm text-gray-500">$ {parseFloat(item.product?.cost || 0).toFixed(2)}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium text-gray-900">$ {parseFloat(item.value || 0).toFixed(2)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
            {loadingMoreInventory && (
              <div className="flex items-center justify-center py-4">
                <Loader2 className="w-5 h-5 animate-spin text-gray-400" />
                <span className="ml-2 text-sm text-gray-500">Cargando más inventario...</span>
              </div>
            )}
            {!hasMoreInventory && inventoryRows.length > 0 && (
              <div className="text-center py-3 text-xs text-gray-400">
                {inventoryRows.length} items cargados
              </div>
            )}
            {hasMoreInventory && <div ref={inventorySentinelRef} className="h-1" />}
          </div>
        );
      case 'purchases':
        return (
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-50">
              <tr>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Número</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Fecha</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Proveedor</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Estado</th>
                <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase">Total</th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {reportData.map((po, index) => (
                <tr key={index}>
                  <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{po.order_number}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{new Date(po.order_date).toLocaleDateString()}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{po.supplier?.name}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{po.status}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium text-gray-900">{po.currency} {parseFloat(po.total || 0).toFixed(2)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        );
      case 'top_products':
        return (
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-50">
              <tr>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">SKU</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Producto</th>
                <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase">Cant. Vendida</th>
                <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase">Monto Total</th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {reportData.map((item, index) => (
                <tr key={index}>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{item.product?.sku}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{item.product?.name}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-right text-sm text-gray-900">{item.total_quantity}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium text-gray-900">$ {parseFloat(item.total_amount || 0).toFixed(2)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        );
      case 'product_sales':
        return (
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-50">
              <tr>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">SKU</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Producto</th>
                <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase">Cant. Vendida</th>
                <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase"># Ventas</th>
                <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase">Total USD</th>
                <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase">Total COP</th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {reportData.map((item, index) => (
                <tr key={index}>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{item.product?.sku}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{item.product?.name}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-right text-sm text-gray-900">{item.total_quantity}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-right text-sm text-gray-900">{item.num_sales}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium text-gray-900">$ {parseFloat(item.total_usd || 0).toFixed(2)}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium text-gray-900">COP {Math.round(item.total_cop || 0).toLocaleString('de-DE')}</td>
                </tr>
              ))}
            </tbody>
          </table>
        );
      case 'low_stock':
        return (
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-50">
              <tr>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">SKU</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Producto</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Almacén</th>
                <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase">Stock Actual</th>
                <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase">Stock Mínimo</th>
                <th className="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase">Estado</th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {reportData.map((item, index) => (
                <tr key={index}>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{item.product?.sku}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{item.product?.name}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{item.warehouse?.name}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium text-red-600">{item.quantity}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-right text-sm text-gray-500">{item.product?.minimum_stock || 0}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-center">
                    <span className="px-2 py-1 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-100 text-red-800">
                      Crítico
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        );
      default:
        return null;
    }
  };

  return (
    <div className="p-6 space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-800">Reportes</h1>
        <p className="text-gray-600 mt-1">Genera y exporta reportes del sistema</p>
      </div>

      <div className="bg-white rounded-lg shadow p-6">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              <Filter className="w-4 h-4 inline mr-1" />
              Tipo de Reporte
            </label>
            <select
              value={reportType}
              onChange={(e) => {
                setReportType(e.target.value);
                setSalesRows([]);
                setSalesStats(null);
                setInventoryRows([]);
                setInventoryStats(null);
                generateReportMutation.reset();
              }}
              className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
            >
              {reportTypes.map(type => (
                <option key={type.value} value={type.value}>
                  {type.label}
                </option>
              ))}
            </select>
          </div>

          {['sales', 'purchases', 'top_products', 'product_sales'].includes(reportType) && (
            <>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  <Calendar className="w-4 h-4 inline mr-1" />
                  Fecha Inicio
                </label>
                <input
                  type="date"
                  value={dateRange.start_date}
                  onChange={(e) => setDateRange({ ...dateRange, start_date: e.target.value })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  <Calendar className="w-4 h-4 inline mr-1" />
                  Fecha Fin
                </label>
                <input
                  type="date"
                  value={dateRange.end_date}
                  onChange={(e) => setDateRange({ ...dateRange, end_date: e.target.value })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>
            </>
          )}
        </div>

        <div className="flex gap-3 mt-6">
          <button
            onClick={() => reportType === 'sales' ? generateSalesReport(dateRange) : reportType === 'inventory' ? generateInventoryReport() : generateReportMutation.mutate({ type: reportType, dateRange })}
            disabled={loading}
            className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50"
          >
            {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <FileText className="w-4 h-4" />}
            {loading ? 'Generando...' : 'Generar Reporte'}
          </button>

          {reportData && reportData.length > 0 && (
            <button
              onClick={exportToCSV}
              disabled={exportingCSV}
              className="flex items-center gap-2 px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 disabled:opacity-50"
            >
              {exportingCSV ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
              {exportingCSV ? 'Exportando...' : 'Exportar CSV'}
            </button>
          )}
        </div>
      </div>

      {renderStatsCards()}

      {(reportData && reportData.length > 0) && (
        <div className="bg-white rounded-lg shadow overflow-hidden">
          <div className="overflow-x-auto">
            {renderReportTable()}
          </div>
        </div>
      )}
    </div>
  );
};

export default ReportsPage;
