import { useState, useEffect, useRef, useCallback } from 'react';
import { useSearchParams } from 'react-router-dom';
import { useMutation } from '@tanstack/react-query';
import { saleService } from '../services/api/saleService';
import { inventoryService } from '../services/api/inventoryService';
import { purchaseOrderService } from '../services/api/purchaseOrderService';
import { toast } from 'sonner';
import {
  FileText, FileCsv, Funnel, TrendUp, Package,
  ShoppingCart, CurrencyDollar, ChartBar
} from '@phosphor-icons/react';
import { Button, Card, DateRangeFilter, Select, Spinner } from '../components/ui';
import { downloadCSV } from '../utils/csvUtils';

const SALES_PAGE_SIZE = 50;
const INVENTORY_PAGE_SIZE = 50;

const REPORT_TYPES = [
  { value: 'sales',         label: 'Reporte de Ventas' },
  { value: 'inventory',     label: 'Inventario Valorizado' },
  { value: 'purchases',     label: 'Reporte de Compras' },
  { value: 'top_products',  label: 'Productos Más Vendidos' },
  { value: 'product_sales', label: 'Ventas por Producto' },
  { value: 'low_stock',     label: 'Productos con Bajo Stock' },
];

const NEEDS_DATES = ['sales', 'purchases', 'top_products', 'product_sales'];

const fmtCOP = (n) => Math.ceil(n || 0).toLocaleString('es-VE');
const fmtDate = (d) => d ? new Date(d).toLocaleDateString('es-VE') : '';

const getCustomerName = (customer) => {
  if (!customer) return 'Cliente General';
  if (customer.type === 'natural') return `${customer.firstName || ''} ${customer.lastName || ''}`.trim() || 'Sin nombre';
  return customer.businessName || customer.tradeName || 'Sin nombre';
};

const getSaleTypeLabel = (type) => {
  if (type === 'mixed') return 'Mixta';
  if (type === 'credit') return 'Crédito';
  return 'Contado';
};

// ─── Stat card ────────────────────────────────────────────────────────────────

const StatCard = ({ label, value }) => (
  <Card variant="compact">
    <p className="text-sm text-gray-600 mb-1">{label}</p>
    <p className="text-2xl font-bold text-gray-900">{value}</p>
  </Card>
);

// ─── Page ────────────────────────────────────────────────────────────────────

const ReportsPage = () => {
  const [searchParams] = useSearchParams();
  const autoGenerated = useRef(false);

  const paramType  = searchParams.get('type');
  const paramStart = searchParams.get('start');
  const paramEnd   = searchParams.get('end');

  const today = new Date().toISOString().split('T')[0];
  const firstOfMonth = (() => {
    const d = new Date();
    return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-01`;
  })();

  const [reportType, setReportType] = useState(paramType || 'sales');
  const [dateRange, setDateRange] = useState({
    start_date: paramStart || firstOfMonth,
    end_date:   paramEnd   || today,
  });

  // Sales state
  const [salesRows, setSalesRows] = useState([]);
  const [salesPage, setSalesPage] = useState(1);
  const [hasMoreSales, setHasMoreSales] = useState(false);
  const [loadingMoreSales, setLoadingMoreSales] = useState(false);
  const [salesStats, setSalesStats] = useState(null);
  const [salesLoading, setSalesLoading] = useState(false);
  const [exportingCSV, setExportingCSV] = useState(false);
  const salesAdjustedRange = useRef(null);

  // Inventory state
  const [inventoryRows, setInventoryRows] = useState([]);
  const [inventoryPage, setInventoryPage] = useState(1);
  const [hasMoreInventory, setHasMoreInventory] = useState(false);
  const [loadingMoreInventory, setLoadingMoreInventory] = useState(false);
  const [inventoryStats, setInventoryStats] = useState(null);
  const [inventoryLoading, setInventoryLoading] = useState(false);

  const getAdjustedRange = (range) => ({
    date_from: range.start_date + 'T00:00:00',
    date_to:   range.end_date   + 'T23:59:59',
  });

  const SALES_STATUS_FILTER = 'completed,pending';

  const generateSalesReport = useCallback(async (range) => {
    const adjusted = { ...getAdjustedRange(range), status: SALES_STATUS_FILTER };
    salesAdjustedRange.current = adjusted;
    setSalesStats(null);
    setSalesRows([]);
    setSalesLoading(true);
    try {
      const [statsRes, salesRes] = await Promise.all([
        saleService.getSalesStats({ ...adjusted, summary_only: 'true' }),
        saleService.getSales({ ...adjusted, page: 1, limit: SALES_PAGE_SIZE })
      ]);
      const total = statsRes.stats?.totalSales || 0;
      const cop   = statsRes.stats?.totalRevenueCOP || 0;
      setSalesStats({
        total_sales:       total,
        total_amount_cop:  cop,
        average_ticket_cop: total > 0 ? cop / total : 0,
      });
      const rows       = salesRes.sales || [];
      const pagination = salesRes.pagination || {};
      setSalesRows(rows);
      setSalesPage(1);
      setHasMoreSales(pagination.page < pagination.totalPages);
    } catch (e) {
      console.error('Error generating sales report:', e);
      toast.error('Error al generar el reporte de ventas');
    } finally {
      setSalesLoading(false);
    }
  }, []);

  const processInventoryItem = (item) => {
    const qty  = parseFloat(item.quantity) || 0;
    const cost = parseFloat(item.product?.cost) || 0;
    return { ...item, quantity: qty, value: qty * cost };
  };

  const generateInventoryReport = useCallback(async () => {
    setInventoryStats(null);
    setInventoryRows([]);
    setInventoryLoading(true);
    try {
      const res        = await inventoryService.getAll({ page: 1, limit: INVENTORY_PAGE_SIZE });
      const items      = (res.data || []).map(processInventoryItem);
      const pagination = res.pagination || {};
      setInventoryRows(items);
      setInventoryPage(1);
      setHasMoreInventory(pagination.page < pagination.totalPages);
      setInventoryStats({ total_items: pagination.total || items.length });
    } catch (e) {
      console.error('Error generating inventory report:', e);
      toast.error('Error al generar el reporte de inventario');
    } finally {
      setInventoryLoading(false);
    }
  }, []);

  const loadMoreInventory = useCallback(async () => {
    if (loadingMoreInventory || !hasMoreInventory) return;
    try {
      setLoadingMoreInventory(true);
      const nextPage   = inventoryPage + 1;
      const res        = await inventoryService.getAll({ page: nextPage, limit: INVENTORY_PAGE_SIZE });
      const items      = (res.data || []).map(processInventoryItem);
      const pagination = res.pagination || {};
      setInventoryRows(prev => [...prev, ...items]);
      setInventoryPage(nextPage);
      setHasMoreInventory(pagination.page < pagination.totalPages);
    } catch (e) {
      console.error('Error loading more inventory:', e);
    } finally {
      setLoadingMoreInventory(false);
    }
  }, [loadingMoreInventory, hasMoreInventory, inventoryPage]);

  const generateReportMutation = useMutation({
    mutationFn: async ({ type, range }) => {
      const adj = getAdjustedRange(range);
      switch (type) {
        case 'purchases': {
          const poRes  = await purchaseOrderService.getAll({ ...adj, limit: 1000 });
          const poList = poRes.data || poRes.purchaseOrders || [];
          const totalAmount = poList.reduce((sum, po) => sum + parseFloat(po.total || 0), 0);
          return {
            stats: {
              total_orders:  poList.length,
              total_amount:  totalAmount,
              average_order: poList.length > 0 ? totalAmount / poList.length : 0,
            },
            data: poList,
          };
        }
        case 'top_products': {
          const statsData   = await saleService.getSalesStats({ ...adj, top_limit: 50 });
          const topProducts = (statsData.stats?.topProducts || []).map(tp => ({
            product:        tp.product,
            total_quantity: parseFloat(tp.dataValues?.total_quantity || tp.total_quantity || 0),
            total_amount:   parseFloat(tp.dataValues?.total_amount   || tp.total_amount   || 0),
          }));
          return {
            stats: {
              total_products:  topProducts.length,
              total_revenue:   topProducts.reduce((s, p) => s + p.total_amount, 0),
              total_units_sold: topProducts.reduce((s, p) => s + p.total_quantity, 0),
            },
            data: topProducts,
          };
        }
        case 'product_sales': {
          const res   = await saleService.getProductSales(adj);
          const items = (res.data || []).map(item => ({
            product:        item.product,
            total_quantity: parseFloat(item.dataValues?.total_quantity || item.total_quantity || 0),
            num_sales:      parseInt(item.dataValues?.num_sales || item.num_sales || 0),
            total_usd:      parseFloat(item.dataValues?.total_usd || item.total_usd || 0),
            total_cop:      Math.ceil(parseFloat(item.dataValues?.total_cop || item.total_cop || 0)),
          }));
          return {
            stats: {
              total_products: items.length,
              total_units:    items.reduce((s, p) => s + p.total_quantity, 0),
              total_usd:      items.reduce((s, p) => s + p.total_usd, 0),
              total_cop:      items.reduce((s, p) => s + p.total_cop, 0),
            },
            data: items,
          };
        }
        case 'low_stock': {
          const res   = await inventoryService.getLowStock({ limit: 1000 });
          const items = res.data || res.inventory || [];
          return { stats: { critical_items: items.length }, data: items };
        }
        default:
          return { stats: null, data: [] };
      }
    },
    onError: (error) => {
      toast.error('Error al generar el reporte');
      console.error('Error generating report:', error);
    },
  });

  const loadMoreSales = useCallback(async () => {
    if (loadingMoreSales || !hasMoreSales || !salesAdjustedRange.current) return;
    try {
      setLoadingMoreSales(true);
      const nextPage   = salesPage + 1;
      const res        = await saleService.getSales({ ...salesAdjustedRange.current, page: nextPage, limit: SALES_PAGE_SIZE });
      const rows       = res.sales || [];
      const pagination = res.pagination || {};
      setSalesRows(prev => [...prev, ...rows]);
      setSalesPage(nextPage);
      setHasMoreSales(pagination.page < pagination.totalPages);
    } catch (e) {
      console.error('Error loading more sales:', e);
    } finally {
      setLoadingMoreSales(false);
    }
  }, [loadingMoreSales, hasMoreSales, salesPage]);

  // Auto-generate when URL has params
  useEffect(() => {
    if (paramType && !autoGenerated.current) {
      autoGenerated.current = true;
      if (reportType === 'sales') generateSalesReport(dateRange);
      else if (reportType === 'inventory') generateInventoryReport();
      else generateReportMutation.mutate({ type: reportType, range: dateRange });
    }
  }, []);

  // Infinite scroll — sales
  const sentinelRef = useRef(null);
  useEffect(() => {
    if (reportType !== 'sales' || !hasMoreSales) return;
    const el = sentinelRef.current;
    if (!el) return;
    const observer = new IntersectionObserver(
      ([e]) => { if (e.isIntersecting) loadMoreSales(); },
      { rootMargin: '200px' }
    );
    observer.observe(el);
    return () => observer.disconnect();
  }, [reportType, hasMoreSales, loadMoreSales]);

  // Infinite scroll — inventory
  const inventorySentinelRef = useRef(null);
  useEffect(() => {
    if (reportType !== 'inventory' || !hasMoreInventory) return;
    const el = inventorySentinelRef.current;
    if (!el) return;
    const observer = new IntersectionObserver(
      ([e]) => { if (e.isIntersecting) loadMoreInventory(); },
      { rootMargin: '200px' }
    );
    observer.observe(el);
    return () => observer.disconnect();
  }, [reportType, hasMoreInventory, loadMoreInventory]);

  const reportResult = generateReportMutation.data;
  const stats      = reportType === 'sales'     ? salesStats
                   : reportType === 'inventory' ? inventoryStats
                   : (reportResult?.stats ?? null);
  const reportData = reportType === 'sales'     ? salesRows
                   : reportType === 'inventory' ? inventoryRows
                   : (reportResult?.data ?? null);
  const loading    = reportType === 'sales'     ? salesLoading
                   : reportType === 'inventory' ? inventoryLoading
                   : generateReportMutation.isPending;

  // ─── CSV export ────────────────────────────────────────────────────────────

  const fetchAllSalesForExport = async () => {
    if (!salesAdjustedRange.current) return [];
    const allSales = [];
    let page = 1, hasMore = true;
    while (hasMore) {
      const res        = await saleService.getSales({ ...salesAdjustedRange.current, page, limit: 200 });
      const pagination = res.pagination || {};
      allSales.push(...(res.sales || []));
      hasMore = pagination.page < pagination.totalPages;
      page++;
    }
    return allSales;
  };

  const fetchAllInventoryForExport = async () => {
    const allItems = [];
    let page = 1, hasMore = true;
    while (hasMore) {
      const res        = await inventoryService.getAll({ page, limit: 200 });
      const pagination = res.pagination || {};
      allItems.push(...(res.data || []).map(processInventoryItem));
      hasMore = pagination.page < pagination.totalPages;
      page++;
    }
    return allItems;
  };

  const exportToCSV = async () => {
    if (!reportData || reportData.length === 0) {
      toast.error('No hay datos para exportar');
      return;
    }
    switch (reportType) {
      case 'sales': {
        setExportingCSV(true);
        try {
          const allSales = await fetchAllSalesForExport();
          downloadCSV(
            `reporte_ventas_${dateRange.start_date}_${dateRange.end_date}`,
            ['Número', 'Fecha', 'Cliente', 'Tipo', 'Estado', 'Total COP'],
            allSales.map(sale => {
              const rate     = parseFloat(sale.exchange_rate) || 1;
              const totalCOP = Math.ceil((parseFloat(sale.total) || 0) * rate);
              return [sale.sale_number, fmtDate(sale.sale_date), getCustomerName(sale.customer), getSaleTypeLabel(sale.sale_type), sale.status, totalCOP];
            })
          );
          toast.success(`${allSales.length} ventas exportadas`);
        } catch (e) {
          console.error('Error exporting sales CSV:', e);
          toast.error('Error al exportar ventas');
        } finally {
          setExportingCSV(false);
        }
        break;
      }
      case 'inventory': {
        setExportingCSV(true);
        try {
          const allItems = await fetchAllInventoryForExport();
          downloadCSV(
            `inventario_valorizado_${today}`,
            ['SKU', 'Producto', 'Almacén', 'Cant. Total', 'Existencia (Paquetes)', 'Existencia (Unidades)', 'Uds/Paquete', 'Costo Unitario', 'Valor Total'],
            allItems.map(item => {
              const presentations       = item.product?.presentations || [];
              const defaultPresentation = presentations.find(p => p.is_default) || presentations[0];
              const unitsPerPackage     = defaultPresentation?.units_per_package || 1;
              const totalUnits          = item.quantity || 0;
              return [item.product?.sku || '', item.product?.name || '', item.warehouse?.name || '', totalUnits, Math.floor(totalUnits / unitsPerPackage), totalUnits % unitsPerPackage, unitsPerPackage, item.product?.cost || 0, item.value || 0];
            })
          );
          toast.success(`${allItems.length} items exportados`);
        } catch (e) {
          console.error('Error exporting inventory CSV:', e);
          toast.error('Error al exportar inventario');
        } finally {
          setExportingCSV(false);
        }
        break;
      }
      case 'purchases':
        downloadCSV(
          `reporte_compras_${dateRange.start_date}_${dateRange.end_date}`,
          ['Número', 'Fecha', 'Proveedor', 'Estado', 'Moneda', 'Total'],
          reportData.map(po => [po.order_number, fmtDate(po.order_date), po.supplier?.name || '', po.status, po.currency, po.total])
        );
        break;
      case 'top_products':
        downloadCSV(
          `productos_mas_vendidos_${dateRange.start_date}_${dateRange.end_date}`,
          ['SKU', 'Producto', 'Cantidad Vendida', 'Monto Total'],
          reportData.map(item => [item.product?.sku || '', item.product?.name || '', item.total_quantity, item.total_amount])
        );
        break;
      case 'product_sales':
        downloadCSV(
          `ventas_por_producto_${dateRange.start_date}_${dateRange.end_date}`,
          ['SKU', 'Producto', 'Cant. Vendida', '# Ventas', 'Total USD', 'Total COP'],
          reportData.map(item => [item.product?.sku || '', item.product?.name || '', item.total_quantity, item.num_sales, parseFloat(item.total_usd || 0).toFixed(2), Math.ceil(item.total_cop || 0)])
        );
        break;
      case 'low_stock':
        downloadCSV(
          `productos_bajo_stock_${today}`,
          ['SKU', 'Producto', 'Almacén', 'Cant. Total', 'Existencia (Paquetes)', 'Existencia (Unidades)', 'Uds/Paquete', 'Stock Mínimo', 'Estado'],
          reportData.map(item => {
            const presentations       = item.product?.presentations || [];
            const defaultPresentation = presentations.find(p => p.is_default) || presentations[0];
            const unitsPerPackage     = defaultPresentation?.units_per_package || 1;
            const totalUnits          = item.quantity || 0;
            return [item.product?.sku || '', item.product?.name || '', item.warehouse?.name || '', totalUnits, Math.floor(totalUnits / unitsPerPackage), totalUnits % unitsPerPackage, unitsPerPackage, item.product?.minimum_stock || 0, 'Crítico'];
          })
        );
        break;
      default:
        break;
    }
  };

  // ─── Stats cards ───────────────────────────────────────────────────────────

  const renderStatsCards = () => {
    if (!stats) return null;
    switch (reportType) {
      case 'sales':
        return (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
            <StatCard label="Total Ventas" value={stats.total_sales} />
            <StatCard label="Monto Total" value={`COP ${fmtCOP(stats.total_amount_cop)}`} />
            <StatCard label="Ticket Promedio" value={`COP ${fmtCOP(stats.average_ticket_cop)}`} />
          </div>
        );
      case 'inventory':
        return (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
            <StatCard label="Total Items" value={stats.total_items} />
          </div>
        );
      case 'purchases':
        return (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
            <StatCard label="Total Órdenes" value={stats.total_orders} />
            <StatCard label="Monto Total" value={`$ ${parseFloat(stats.total_amount || 0).toFixed(2)}`} />
            <StatCard label="Promedio por Orden" value={`$ ${parseFloat(stats.average_order || 0).toFixed(2)}`} />
          </div>
        );
      case 'top_products':
        return (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
            <StatCard label="Total Productos" value={stats.total_products} />
            <StatCard label="Unidades Vendidas" value={stats.total_units_sold} />
            <StatCard label="Ingresos Totales" value={`$ ${parseFloat(stats.total_revenue || 0).toFixed(2)}`} />
          </div>
        );
      case 'product_sales':
        return (
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
            <StatCard label="Total Productos" value={stats.total_products} />
            <StatCard label="Total Unidades" value={stats.total_units} />
            <StatCard label="Total USD" value={`$ ${parseFloat(stats.total_usd || 0).toFixed(2)}`} />
            <StatCard label="Total COP" value={`COP ${fmtCOP(stats.total_cop)}`} />
          </div>
        );
      case 'low_stock':
        return (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
            <Card variant="compact">
              <p className="text-sm text-gray-600 mb-1">Items Críticos</p>
              <p className="text-2xl font-bold text-red-600">{stats.critical_items}</p>
            </Card>
          </div>
        );
      default:
        return null;
    }
  };

  // ─── Report table ──────────────────────────────────────────────────────────

  const renderReportTable = () => {
    if (!reportData || reportData.length === 0) {
      return <div className="text-center py-12 text-gray-500">No hay datos para mostrar</div>;
    }

    const TH = ({ children, right }) => (
      <th className={`px-6 py-3 text-${right ? 'right' : 'left'} text-xs font-medium text-gray-500 uppercase`}>{children}</th>
    );

    switch (reportType) {
      case 'sales':
        return (
          <div>
            <table className="min-w-full divide-y divide-gray-200">
              <thead className="bg-gray-50">
                <tr>
                  <TH>Número</TH><TH>Fecha</TH><TH>Cliente</TH><TH>Tipo</TH><TH right>Total</TH>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {salesRows.map((sale, i) => (
                  <tr key={i}>
                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{sale.sale_number}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{fmtDate(sale.sale_date)}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{getCustomerName(sale.customer)}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{getSaleTypeLabel(sale.sale_type)}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium text-gray-900">
                      COP {fmtCOP((parseFloat(sale.total) || 0) * (parseFloat(sale.exchange_rate) || 1))}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
            {loadingMoreSales && (
              <div className="flex items-center justify-center gap-2 py-4 text-sm text-gray-500">
                <Spinner size="sm" /> Cargando más ventas...
              </div>
            )}
            {!hasMoreSales && salesRows.length > 0 && (
              <div className="text-center py-3 text-xs text-gray-400">{salesRows.length} ventas cargadas</div>
            )}
            {hasMoreSales && <div ref={sentinelRef} className="h-1" />}
          </div>
        );

      case 'inventory':
        return (
          <div>
            <table className="min-w-full divide-y divide-gray-200">
              <thead className="bg-gray-50">
                <tr>
                  <TH>SKU</TH><TH>Producto</TH><TH>Almacén</TH>
                  <TH right>Cantidad</TH><TH right>Costo Unit.</TH><TH right>Valor Total</TH>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {inventoryRows.map((item, i) => (
                  <tr key={i}>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{item.product?.sku}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{item.product?.name}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{item.warehouse?.name}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-right text-sm text-gray-900">{item.quantity}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-right text-sm text-gray-500">$ {parseFloat(item.product?.cost || 0).toFixed(2)}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium text-gray-900">$ {parseFloat(item.value || 0).toFixed(2)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
            {loadingMoreInventory && (
              <div className="flex items-center justify-center gap-2 py-4 text-sm text-gray-500">
                <Spinner size="sm" /> Cargando más inventario...
              </div>
            )}
            {!hasMoreInventory && inventoryRows.length > 0 && (
              <div className="text-center py-3 text-xs text-gray-400">{inventoryRows.length} items cargados</div>
            )}
            {hasMoreInventory && <div ref={inventorySentinelRef} className="h-1" />}
          </div>
        );

      case 'purchases':
        return (
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-50">
              <tr><TH>Número</TH><TH>Fecha</TH><TH>Proveedor</TH><TH>Estado</TH><TH right>Total</TH></tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {reportData.map((po, i) => (
                <tr key={i}>
                  <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{po.order_number}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{fmtDate(po.order_date)}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{po.supplier?.name}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{po.status}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium text-gray-900">{po.currency} {parseFloat(po.total || 0).toFixed(2)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        );

      case 'top_products':
        return (
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-50">
              <tr><TH>SKU</TH><TH>Producto</TH><TH right>Cant. Vendida</TH><TH right>Monto Total</TH></tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {reportData.map((item, i) => (
                <tr key={i}>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{item.product?.sku}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{item.product?.name}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-right text-sm text-gray-900">{item.total_quantity}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium text-gray-900">$ {parseFloat(item.total_amount || 0).toFixed(2)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        );

      case 'product_sales':
        return (
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-50">
              <tr>
                <TH>SKU</TH><TH>Producto</TH>
                <TH right>Cant. Vendida</TH><TH right># Ventas</TH>
                <TH right>Total USD</TH><TH right>Total COP</TH>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {reportData.map((item, i) => (
                <tr key={i}>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{item.product?.sku}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{item.product?.name}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-right text-sm text-gray-900">{item.total_quantity}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-right text-sm text-gray-900">{item.num_sales}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium text-gray-900">$ {parseFloat(item.total_usd || 0).toFixed(2)}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium text-gray-900">COP {fmtCOP(item.total_cop)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        );

      case 'low_stock':
        return (
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-50">
              <tr>
                <TH>SKU</TH><TH>Producto</TH><TH>Almacén</TH>
                <TH right>Stock Actual</TH><TH right>Stock Mínimo</TH><TH>Estado</TH>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {reportData.map((item, i) => (
                <tr key={i}>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{item.product?.sku}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{item.product?.name}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{item.warehouse?.name}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium text-red-600">{item.quantity}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-right text-sm text-gray-500">{item.product?.minimum_stock || 0}</td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <span className="px-2 py-1 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-100 text-red-800">
                      Crítico
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        );

      default:
        return null;
    }
  };

  const handleGenerate = () => {
    if (reportType === 'sales') generateSalesReport(dateRange);
    else if (reportType === 'inventory') generateInventoryReport();
    else generateReportMutation.mutate({ type: reportType, range: dateRange });
  };

  const handleReportTypeChange = (value) => {
    setReportType(value);
    setSalesRows([]);
    setSalesStats(null);
    setInventoryRows([]);
    setInventoryStats(null);
    generateReportMutation.reset();
  };

  // ─── Render ────────────────────────────────────────────────────────────────

  return (
    <div className="p-6 space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-800">Reportes</h1>
        <p className="text-gray-600 mt-1">Genera y exporta reportes del sistema</p>
      </div>

      {/* Funnel area */}
      <Card>
        <div className="flex flex-wrap items-end gap-4">
          {/* Report type */}
          <div className="min-w-[200px]">
            <label className="block text-xs font-medium text-gray-600 mb-1">
              <Funnel className="w-3.5 h-3.5 inline mr-1" />
              Tipo de Reporte
            </label>
            <Select
              value={reportType}
              onChange={(e) => handleReportTypeChange(e.target.value)}
              options={REPORT_TYPES}
            />
          </div>

          {/* Date range */}
          {NEEDS_DATES.includes(reportType) && (
            <DateRangeFilter
              startDate={dateRange.start_date}
              endDate={dateRange.end_date}
              onChange={({ start_date, end_date }) => setDateRange({ start_date, end_date })}
              showPresets
            />
          )}
        </div>

        {/* Actions */}
        <div className="flex gap-3 mt-5 pt-4 border-t border-gray-100">
          <Button loading={loading} onClick={handleGenerate} disabled={loading}>
            <FileText className="w-4 h-4" />
            {loading ? 'Generando...' : 'Generar Reporte'}
          </Button>
          {reportData && reportData.length > 0 && (
            <Button variant="secondary" size="icon" loading={exportingCSV} onClick={exportToCSV} disabled={exportingCSV} title="Exportar CSV">
              <FileCsv className="w-4 h-4 text-emerald-600" />
            </Button>
          )}
        </div>
      </Card>

      {/* Stats */}
      {renderStatsCards()}

      {/* Table */}
      {reportData && reportData.length > 0 && (
        <div className="bg-white rounded-lg shadow overflow-hidden">
          <div className="overflow-x-auto">
            {renderReportTable()}
          </div>
        </div>
      )}
    </div>
  );
};

export default ReportsPage;
